-- RM Sales-Stock Data Warehouse v1
-- Run this file against the separate warehouse_db PostgreSQL database.
BEGIN;

CREATE SCHEMA IF NOT EXISTS etl;
CREATE SCHEMA IF NOT EXISTS stg;
CREATE SCHEMA IF NOT EXISTS dw;
CREATE SCHEMA IF NOT EXISTS mart;

CREATE TABLE IF NOT EXISTS etl.load_batch (
  batch_id UUID PRIMARY KEY,
  source_system TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'SUCCEEDED_WITH_REJECTS', 'FAILED')),
  source_window_started_at TIMESTAMPTZ,
  source_window_ended_at TIMESTAMPTZ,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  row_counts JSONB NOT NULL DEFAULT '{}'::JSONB,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS etl.watermark (
  source_system TEXT NOT NULL,
  entity_name TEXT NOT NULL,
  last_changed_at TIMESTAMPTZ NOT NULL,
  last_source_id BIGINT NOT NULL,
  last_successful_batch_id UUID NOT NULL REFERENCES etl.load_batch(batch_id),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (source_system, entity_name)
);

CREATE TABLE IF NOT EXISTS etl.rejected_row (
  rejected_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id UUID NOT NULL REFERENCES etl.load_batch(batch_id),
  entity_name TEXT NOT NULL,
  source_id BIGINT NOT NULL,
  reason TEXT NOT NULL,
  payload JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (batch_id, entity_name, source_id, reason)
);

CREATE INDEX IF NOT EXISTS etl_rejected_row_batch_idx
  ON etl.rejected_row (batch_id, entity_name);

-- The scheduler supplies UUID batch_id values; no extension is required.
CREATE OR REPLACE FUNCTION etl.business_date(p_at TIMESTAMPTZ)
RETURNS DATE
LANGUAGE SQL
STABLE
RETURNS NULL ON NULL INPUT
AS $$
  SELECT (p_at AT TIME ZONE 'Asia/Bangkok')::DATE;
$$;

CREATE OR REPLACE FUNCTION etl.date_key(p_at TIMESTAMPTZ)
RETURNS INTEGER
LANGUAGE SQL
STABLE
RETURNS NULL ON NULL INPUT
AS $$
  SELECT TO_CHAR(etl.business_date(p_at), 'YYYYMMDD')::INTEGER;
$$;

CREATE TABLE IF NOT EXISTS dw.dim_date (
  date_key INTEGER PRIMARY KEY,
  calendar_date DATE NOT NULL UNIQUE,
  calendar_year SMALLINT NOT NULL,
  calendar_quarter SMALLINT NOT NULL,
  calendar_month SMALLINT NOT NULL,
  month_name TEXT NOT NULL,
  week_of_year SMALLINT NOT NULL,
  week_start_date DATE NOT NULL,
  day_of_month SMALLINT NOT NULL,
  iso_day_of_week SMALLINT NOT NULL,
  is_weekend BOOLEAN NOT NULL
);

CREATE OR REPLACE FUNCTION etl.ensure_dates(p_dates DATE[])
RETURNS VOID
LANGUAGE SQL
AS $$
  INSERT INTO dw.dim_date (
    date_key, calendar_date, calendar_year, calendar_quarter, calendar_month,
    month_name, week_of_year, week_start_date, day_of_month, iso_day_of_week, is_weekend
  )
  SELECT
    TO_CHAR(d, 'YYYYMMDD')::INTEGER,
    d,
    EXTRACT(YEAR FROM d)::SMALLINT,
    EXTRACT(QUARTER FROM d)::SMALLINT,
    EXTRACT(MONTH FROM d)::SMALLINT,
    TO_CHAR(d, 'FMMonth'),
    EXTRACT(WEEK FROM d)::SMALLINT,
    DATE_TRUNC('week', d)::DATE,
    EXTRACT(DAY FROM d)::SMALLINT,
    EXTRACT(ISODOW FROM d)::SMALLINT,
    EXTRACT(ISODOW FROM d) IN (6, 7)
  FROM (
    SELECT DISTINCT unnest(p_dates) AS d
  ) AS dates
  WHERE d IS NOT NULL
  ON CONFLICT (date_key) DO NOTHING;
$$;

SELECT etl.ensure_dates(ARRAY(
  SELECT d::DATE
  FROM generate_series(DATE '2020-01-01', DATE '2035-12-31', INTERVAL '1 day') AS d
));

CREATE TABLE IF NOT EXISTS dw.dim_channel (
  channel_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system TEXT NOT NULL,
  channel_source_id BIGINT NOT NULL,
  channel_code TEXT,
  channel_name TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  source_updated_at TIMESTAMPTZ NOT NULL,
  last_loaded_batch_id UUID REFERENCES etl.load_batch(batch_id),
  UNIQUE (source_system, channel_source_id)
);

CREATE TABLE IF NOT EXISTS dw.dim_sku (
  sku_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system TEXT NOT NULL,
  sku_source_id BIGINT NOT NULL,
  sku_code TEXT,
  product_source_id BIGINT,
  product_name TEXT,
  category_source_id BIGINT,
  category_name TEXT,
  attribute_value TEXT,
  size_value TEXT,
  unit_cost NUMERIC(18, 2),
  selling_price NUMERIC(18, 2),
  min_stock_level INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  source_updated_at TIMESTAMPTZ NOT NULL,
  last_loaded_batch_id UUID REFERENCES etl.load_batch(batch_id),
  UNIQUE (source_system, sku_source_id)
);

CREATE TABLE IF NOT EXISTS dw.dim_customer (
  customer_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system TEXT NOT NULL,
  customer_source_id BIGINT NOT NULL,
  customer_name TEXT,
  latest_province_name TEXT,
  latest_postal_code TEXT,
  source_updated_at TIMESTAMPTZ NOT NULL,
  last_loaded_batch_id UUID REFERENCES etl.load_batch(batch_id),
  UNIQUE (source_system, customer_source_id)
);

INSERT INTO dw.dim_channel (
  channel_key, source_system, channel_source_id, channel_code, channel_name,
  is_active, is_deleted, source_updated_at
)
VALUES (0, '__unknown__', 0, 'UNKNOWN', 'Unknown channel', FALSE, FALSE, '-infinity')
ON CONFLICT (channel_key) DO NOTHING;

INSERT INTO dw.dim_sku (
  sku_key, source_system, sku_source_id, sku_code, product_name,
  min_stock_level, is_active, is_deleted, source_updated_at
)
VALUES (0, '__unknown__', 0, 'UNKNOWN', 'Unknown SKU', 0, FALSE, FALSE, '-infinity')
ON CONFLICT (sku_key) DO NOTHING;

INSERT INTO dw.dim_customer (
  customer_key, source_system, customer_source_id, customer_name, source_updated_at
)
VALUES (0, '__unknown__', 0, 'Unknown customer', '-infinity')
ON CONFLICT (customer_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS dw.fact_order (
  order_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system TEXT NOT NULL,
  order_source_id BIGINT NOT NULL,
  order_number TEXT,
  order_at TIMESTAMPTZ NOT NULL,
  order_date_key INTEGER NOT NULL REFERENCES dw.dim_date(date_key),
  channel_key BIGINT NOT NULL REFERENCES dw.dim_channel(channel_key),
  customer_key BIGINT NOT NULL DEFAULT 0 REFERENCES dw.dim_customer(customer_key),
  buyer_source_id BIGINT,
  buyer_name TEXT,
  province_name TEXT,
  postal_code TEXT,
  current_status TEXT NOT NULL,
  is_cancelled BOOLEAN NOT NULL DEFAULT FALSE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  delivered_at TIMESTAMPTZ,
  delivered_date_key INTEGER REFERENCES dw.dim_date(date_key),
  delivery_timestamp_source TEXT
    CHECK (delivery_timestamp_source IN ('HISTORY', 'ORDER_UPDATED_AT_ESTIMATE')),
  return_received_at TIMESTAMPTZ,
  subtotal_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  shipping_fee_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  source_updated_at TIMESTAMPTZ NOT NULL,
  last_loaded_batch_id UUID REFERENCES etl.load_batch(batch_id),
  UNIQUE (source_system, order_source_id)
);

-- Keep re-running bootstrap safe for an already-created warehouse.
ALTER TABLE dw.fact_order ADD COLUMN IF NOT EXISTS buyer_source_id BIGINT;
ALTER TABLE dw.fact_order ADD COLUMN IF NOT EXISTS buyer_name TEXT;
ALTER TABLE dw.fact_order ADD COLUMN IF NOT EXISTS province_name TEXT;
ALTER TABLE dw.fact_order ADD COLUMN IF NOT EXISTS postal_code TEXT;
ALTER TABLE dw.fact_order ADD COLUMN IF NOT EXISTS customer_key BIGINT DEFAULT 0;
ALTER TABLE dw.fact_order ADD COLUMN IF NOT EXISTS return_received_at TIMESTAMPTZ;

CREATE OR REPLACE FUNCTION etl.backfill_customer_dimension()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  WITH latest_customer AS (
    SELECT DISTINCT ON (source_system, buyer_source_id)
      source_system,
      buyer_source_id AS customer_source_id,
      buyer_name AS customer_name,
      province_name AS latest_province_name,
      postal_code AS latest_postal_code,
      source_updated_at,
      last_loaded_batch_id
    FROM dw.fact_order
    WHERE buyer_source_id IS NOT NULL
    ORDER BY source_system, buyer_source_id, source_updated_at DESC, order_source_id DESC
  )
  INSERT INTO dw.dim_customer (
    source_system, customer_source_id, customer_name, latest_province_name,
    latest_postal_code, source_updated_at, last_loaded_batch_id
  )
  SELECT
    source_system, customer_source_id, customer_name, latest_province_name,
    latest_postal_code, source_updated_at, last_loaded_batch_id
  FROM latest_customer
  ON CONFLICT (source_system, customer_source_id) DO UPDATE SET
    customer_name = EXCLUDED.customer_name,
    latest_province_name = EXCLUDED.latest_province_name,
    latest_postal_code = EXCLUDED.latest_postal_code,
    source_updated_at = EXCLUDED.source_updated_at,
    last_loaded_batch_id = EXCLUDED.last_loaded_batch_id
  WHERE EXCLUDED.source_updated_at >= dw.dim_customer.source_updated_at;

  UPDATE dw.fact_order AS orders
  SET customer_key = customers.customer_key
  FROM dw.dim_customer AS customers
  WHERE customers.source_system = orders.source_system
    AND customers.customer_source_id = orders.buyer_source_id
    AND orders.customer_key IS DISTINCT FROM customers.customer_key;
END;
$$;

SELECT etl.backfill_customer_dimension();

UPDATE dw.fact_order SET customer_key = 0 WHERE customer_key IS NULL;
ALTER TABLE dw.fact_order ALTER COLUMN customer_key SET DEFAULT 0;
ALTER TABLE dw.fact_order ALTER COLUMN customer_key SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'dw.fact_order'::regclass
      AND conname = 'fact_order_customer_key_fkey'
  ) THEN
    ALTER TABLE dw.fact_order
      ADD CONSTRAINT fact_order_customer_key_fkey
      FOREIGN KEY (customer_key) REFERENCES dw.dim_customer(customer_key);
  END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS fact_order_order_date_channel_idx
  ON dw.fact_order (order_date_key, channel_key);
CREATE INDEX IF NOT EXISTS fact_order_customer_date_idx
  ON dw.fact_order (customer_key, order_date_key);
CREATE INDEX IF NOT EXISTS fact_order_province_date_idx
  ON dw.fact_order (province_name, order_date_key);
CREATE INDEX IF NOT EXISTS fact_order_delivered_date_channel_idx
  ON dw.fact_order (delivered_date_key, channel_key)
  WHERE delivered_date_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS dw.fact_order_line (
  order_line_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system TEXT NOT NULL,
  order_line_source_id BIGINT NOT NULL,
  order_key BIGINT NOT NULL REFERENCES dw.fact_order(order_key),
  sku_key BIGINT NOT NULL REFERENCES dw.dim_sku(sku_key),
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(18, 2) NOT NULL,
  line_discount_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  line_subtotal_amount NUMERIC(18, 2) NOT NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  source_updated_at TIMESTAMPTZ NOT NULL,
  last_loaded_batch_id UUID REFERENCES etl.load_batch(batch_id),
  UNIQUE (source_system, order_line_source_id)
);

CREATE INDEX IF NOT EXISTS fact_order_line_order_idx ON dw.fact_order_line (order_key);
CREATE INDEX IF NOT EXISTS fact_order_line_sku_idx ON dw.fact_order_line (sku_key);

-- Facebook CF evidence and payment events are retained independently from the
-- mutable order status so the social-payment cohort can be rebuilt idempotently.
CREATE TABLE IF NOT EXISTS dw.fact_facebook_reserve (
  facebook_reserve_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system TEXT NOT NULL,
  reserve_source_id BIGINT NOT NULL,
  order_source_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL,
  reserved_until TIMESTAMPTZ,
  status TEXT NOT NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  source_updated_at TIMESTAMPTZ NOT NULL,
  last_loaded_batch_id UUID REFERENCES etl.load_batch(batch_id),
  UNIQUE (source_system, reserve_source_id)
);

CREATE INDEX IF NOT EXISTS fact_facebook_reserve_order_idx
  ON dw.fact_facebook_reserve (source_system, order_source_id, created_at);

CREATE TABLE IF NOT EXISTS dw.fact_payment_transaction (
  payment_transaction_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system TEXT NOT NULL,
  payment_source_id BIGINT NOT NULL,
  order_source_id BIGINT NOT NULL,
  amount NUMERIC(18, 2) NOT NULL,
  current_status TEXT NOT NULL,
  payment_at TIMESTAMPTZ,
  verified_at TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  source_updated_at TIMESTAMPTZ NOT NULL,
  last_loaded_batch_id UUID REFERENCES etl.load_batch(batch_id),
  UNIQUE (source_system, payment_source_id)
);

CREATE INDEX IF NOT EXISTS fact_payment_transaction_order_idx
  ON dw.fact_payment_transaction (source_system, order_source_id, payment_at, payment_source_id);

CREATE TABLE IF NOT EXISTS dw.fact_order_status_event (
  order_status_event_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system TEXT NOT NULL,
  event_source_id BIGINT NOT NULL,
  order_source_id BIGINT NOT NULL,
  new_status TEXT NOT NULL,
  action TEXT,
  occurred_at TIMESTAMPTZ NOT NULL,
  source_updated_at TIMESTAMPTZ NOT NULL,
  last_loaded_batch_id UUID REFERENCES etl.load_batch(batch_id),
  UNIQUE (source_system, event_source_id)
);

CREATE INDEX IF NOT EXISTS fact_order_status_event_order_idx
  ON dw.fact_order_status_event (source_system, order_source_id, occurred_at);

-- Exactly one current social-CF summary fact per Facebook order.
CREATE TABLE IF NOT EXISTS dw.fact_social_order (
  social_order_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system TEXT NOT NULL,
  order_source_id BIGINT NOT NULL,
  cf_at TIMESTAMPTZ,
  payment_due_at TIMESTAMPTZ,
  required_amount NUMERIC(18, 2) NOT NULL,
  confirmed_paid_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  paid_in_full_at TIMESTAMPTZ,
  is_cod BOOLEAN NOT NULL DEFAULT FALSE,
  is_cancelled BOOLEAN NOT NULL DEFAULT FALSE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  is_data_complete BOOLEAN NOT NULL DEFAULT FALSE,
  snapshot_as_of TIMESTAMPTZ NOT NULL,
  last_loaded_batch_id UUID REFERENCES etl.load_batch(batch_id),
  UNIQUE (source_system, order_source_id)
);

ALTER TABLE dw.fact_social_order ALTER COLUMN cf_at DROP NOT NULL;

CREATE INDEX IF NOT EXISTS fact_social_order_cf_date_idx
  ON dw.fact_social_order (source_system, cf_at, order_source_id);

CREATE TABLE IF NOT EXISTS dw.fact_inventory_movement (
  inventory_movement_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system TEXT NOT NULL,
  movement_source_id BIGINT NOT NULL,
  sku_key BIGINT NOT NULL REFERENCES dw.dim_sku(sku_key),
  movement_at TIMESTAMPTZ NOT NULL,
  movement_date_key INTEGER NOT NULL REFERENCES dw.dim_date(date_key),
  on_hand_delta INTEGER NOT NULL,
  reserved_delta INTEGER NOT NULL DEFAULT 0,
  on_hand_before INTEGER NOT NULL,
  on_hand_after INTEGER NOT NULL,
  reserved_before INTEGER NOT NULL,
  reserved_after INTEGER NOT NULL,
  inventory_version INTEGER NOT NULL,
  operation TEXT NOT NULL,
  reason TEXT NOT NULL,
  source_name TEXT NOT NULL,
  reference_type TEXT,
  reference_id TEXT,
  last_loaded_batch_id UUID REFERENCES etl.load_batch(batch_id),
  UNIQUE (source_system, movement_source_id)
);

CREATE INDEX IF NOT EXISTS fact_inventory_movement_date_sku_idx
  ON dw.fact_inventory_movement (movement_date_key, sku_key);

CREATE TABLE IF NOT EXISTS dw.fact_inventory_daily_snapshot (
  snapshot_date_key INTEGER NOT NULL REFERENCES dw.dim_date(date_key),
  sku_key BIGINT NOT NULL REFERENCES dw.dim_sku(sku_key),
  captured_at TIMESTAMPTZ NOT NULL,
  on_hand_quantity INTEGER NOT NULL,
  reserved_quantity INTEGER NOT NULL,
  available_quantity INTEGER NOT NULL,
  min_stock_level INTEGER NOT NULL,
  is_low_stock BOOLEAN NOT NULL,
  last_loaded_batch_id UUID REFERENCES etl.load_batch(batch_id),
  PRIMARY KEY (snapshot_date_key, sku_key),
  CHECK (available_quantity = GREATEST(on_hand_quantity - reserved_quantity, 0))
);

CREATE TABLE IF NOT EXISTS dw.fact_channel_inventory_daily_snapshot (
  snapshot_date_key INTEGER NOT NULL REFERENCES dw.dim_date(date_key),
  sku_key BIGINT NOT NULL REFERENCES dw.dim_sku(sku_key),
  channel_key BIGINT NOT NULL REFERENCES dw.dim_channel(channel_key),
  captured_at TIMESTAMPTZ NOT NULL,
  allocated_quantity INTEGER NOT NULL,
  allocated_reserved_quantity INTEGER NOT NULL,
  safety_stock_quantity INTEGER NOT NULL,
  target_quantity INTEGER NOT NULL,
  remote_quantity INTEGER,
  available_quantity INTEGER NOT NULL,
  inventory_dirty BOOLEAN NOT NULL,
  is_active BOOLEAN NOT NULL,
  last_loaded_batch_id UUID REFERENCES etl.load_batch(batch_id),
  PRIMARY KEY (snapshot_date_key, sku_key, channel_key)
);

-- Staging carries only the buyer fields needed for analytics; it excludes address
-- lines, phone, email, credentials, tokens, and payment data.
CREATE TABLE IF NOT EXISTS stg.sales_channels (
  batch_id UUID NOT NULL REFERENCES etl.load_batch(batch_id),
  source_id BIGINT NOT NULL,
  code TEXT,
  name TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  deleted_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (batch_id, source_id)
);

CREATE TABLE IF NOT EXISTS stg.skus (
  batch_id UUID NOT NULL REFERENCES etl.load_batch(batch_id),
  source_id BIGINT NOT NULL,
  sku_code TEXT,
  product_source_id BIGINT,
  product_name TEXT,
  category_source_id BIGINT,
  category_name TEXT,
  attribute_value TEXT,
  size_value TEXT,
  unit_cost NUMERIC(18, 2),
  selling_price NUMERIC(18, 2),
  on_hand_quantity INTEGER NOT NULL,
  reserved_quantity INTEGER NOT NULL,
  min_stock_level INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  deleted_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ NOT NULL,
  as_of_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (batch_id, source_id)
);

CREATE TABLE IF NOT EXISTS stg.orders (
  batch_id UUID NOT NULL REFERENCES etl.load_batch(batch_id),
  source_id BIGINT NOT NULL,
  order_number TEXT,
  order_at TIMESTAMPTZ NOT NULL,
  current_status TEXT NOT NULL,
  channel_source_id BIGINT,
  buyer_source_id BIGINT,
  buyer_name TEXT,
  province_name TEXT,
  postal_code TEXT,
  return_received_at TIMESTAMPTZ,
  subtotal_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  shipping_fee_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  deleted_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (batch_id, source_id)
);

ALTER TABLE stg.orders ADD COLUMN IF NOT EXISTS buyer_source_id BIGINT;
ALTER TABLE stg.orders ADD COLUMN IF NOT EXISTS buyer_name TEXT;
ALTER TABLE stg.orders ADD COLUMN IF NOT EXISTS province_name TEXT;
ALTER TABLE stg.orders ADD COLUMN IF NOT EXISTS postal_code TEXT;
ALTER TABLE stg.orders ADD COLUMN IF NOT EXISTS return_received_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS stg.order_status_history (
  batch_id UUID NOT NULL REFERENCES etl.load_batch(batch_id),
  source_id BIGINT NOT NULL,
  order_source_id BIGINT NOT NULL,
  new_status TEXT NOT NULL,
  action TEXT,
  occurred_at TIMESTAMPTZ NOT NULL,
  source_updated_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (batch_id, source_id)
);

ALTER TABLE stg.order_status_history ADD COLUMN IF NOT EXISTS action TEXT;
ALTER TABLE stg.order_status_history ADD COLUMN IF NOT EXISTS source_updated_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS stg.order_lines (
  batch_id UUID NOT NULL REFERENCES etl.load_batch(batch_id),
  source_id BIGINT NOT NULL,
  order_source_id BIGINT NOT NULL,
  sku_source_id BIGINT NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(18, 2) NOT NULL,
  line_discount_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
  line_subtotal_amount NUMERIC(18, 2) NOT NULL,
  deleted_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (batch_id, source_id)
);

CREATE TABLE IF NOT EXISTS stg.facebook_reserves (
  batch_id UUID NOT NULL REFERENCES etl.load_batch(batch_id),
  source_id BIGINT NOT NULL,
  order_source_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL,
  reserved_until TIMESTAMPTZ,
  status TEXT NOT NULL,
  deleted_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (batch_id, source_id)
);

CREATE TABLE IF NOT EXISTS stg.payment_transactions (
  batch_id UUID NOT NULL REFERENCES etl.load_batch(batch_id),
  source_id BIGINT NOT NULL,
  order_source_id BIGINT NOT NULL,
  amount NUMERIC(18, 2) NOT NULL,
  current_status TEXT NOT NULL,
  payment_at TIMESTAMPTZ,
  verified_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (batch_id, source_id)
);

CREATE TABLE IF NOT EXISTS stg.inventory_movements (
  batch_id UUID NOT NULL REFERENCES etl.load_batch(batch_id),
  source_id BIGINT NOT NULL,
  sku_source_id BIGINT NOT NULL,
  movement_at TIMESTAMPTZ NOT NULL,
  on_hand_delta INTEGER NOT NULL,
  reserved_delta INTEGER NOT NULL DEFAULT 0,
  on_hand_before INTEGER NOT NULL,
  on_hand_after INTEGER NOT NULL,
  reserved_before INTEGER NOT NULL,
  reserved_after INTEGER NOT NULL,
  inventory_version INTEGER NOT NULL,
  operation TEXT NOT NULL,
  reason TEXT NOT NULL,
  source_name TEXT NOT NULL,
  reference_type TEXT,
  reference_id TEXT,
  PRIMARY KEY (batch_id, source_id)
);

CREATE TABLE IF NOT EXISTS stg.sku_on_channel (
  batch_id UUID NOT NULL REFERENCES etl.load_batch(batch_id),
  sku_source_id BIGINT NOT NULL,
  channel_source_id BIGINT NOT NULL,
  allocated_quantity INTEGER NOT NULL DEFAULT 0,
  allocated_reserved_quantity INTEGER NOT NULL DEFAULT 0,
  safety_stock_quantity INTEGER NOT NULL DEFAULT 0,
  target_quantity INTEGER NOT NULL DEFAULT 0,
  remote_quantity INTEGER,
  available_quantity INTEGER NOT NULL DEFAULT 0,
  inventory_dirty BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  deleted_at TIMESTAMPTZ,
  source_updated_at TIMESTAMPTZ NOT NULL,
  as_of_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (batch_id, sku_source_id, channel_source_id)
);

CREATE INDEX IF NOT EXISTS stg_orders_batch_idx ON stg.orders (batch_id, source_updated_at, source_id);
CREATE INDEX IF NOT EXISTS stg_order_lines_batch_idx ON stg.order_lines (batch_id, source_updated_at, source_id);
CREATE INDEX IF NOT EXISTS stg_inventory_movements_batch_idx ON stg.inventory_movements (batch_id, movement_at, source_id);

COMMIT;
